// <auto-generated />
namespace GigHub2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FolloingModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FolloingModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201808272037574_FolloingModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
